id: 45ba82e39fda41efa30b086eb174f92c
initial_creation_type: ocr
source_metadata:
  volumes:
    403a399d549f4af1864cf1ecdfeeb42a:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: མདོ་ཀུན་ལས་བཏུས་པ།
      total_pages: 1902
      volume_number: 64
